name: sip bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update

      # Step 4: Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run scraping script
      - name: Run main script
        run: python main.py

      # Step 6: Commit changes to novosti.md
      - name: Commit changes
        uses: lazarevicOgnjen/git-auto-commit-action@v6
        with:
          commit_message: Update novosti.md
          file_pattern: novosti.md
        id: auto-commit-action

      # Step 7: Take screenshot if changes detected
      - name: Take photo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: python photo.py

      # Step 8: Notify via Discord bot
      - name: Discord bot notification
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          WEBHOOK_MAIN: ${{ secrets.WEBHOOK_MAIN }}
        run: python discord.py
